//You are given two strings s and t.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Return the letter that was added to t.
//
// 
//
//Example 1:
//
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//Example 2:
//
//Input: s = "", t = "y"
//Output: "y"
// 
//
//Constraints:
//
//0 <= s.length <= 1000
//t.length == s.length + 1
//s and t consist of lowercase English letters.
//

//Runtime: 0 ms, faster than 100.00% of Go online submissions for Find the Difference.
//Memory Usage: 2.2 MB, less than 95.41% of Go online submissions for Find the Difference.

func findTheDifference(s string, t string) byte {
    s1:=0
    s2:=0
    i:=0
    for ;i<len(s);i++ {
        s1=s1+int(s[i])
        s2=s2+int(t[i])
    }
    s2=s2+int(t[i])
    return byte(s2-s1)
}
